name: Release

on:
    push:
        branches: 
            - main
            - 'feature/development'

jobs:
    build:
        name: Build website using HUGO
        runs-on: ubuntu-latest
        steps:
            - name: Install HUGO
              run: |
                sudo apt install hugo
                hugo version

            - name: Checkout Repository
              uses: actions/checkout@v4
              
            - name: Setup AWS CLI
              uses: sagarsthorat/aws-cli@v1
              with:
                region: 'eu-west-1'
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-cli-version: latest
                output-format: json

            - name: Verify AWS CLI
              run: aws s3 ls

              

