name: Release

on:
    push:
        branches: 
            - main
            - 'feature/development'

jobs:
    build:
        name: Build website using HUGO
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install HUGO
              run: |
                sudo apt install hugo
                pwd
                ls -larth


            # - name: Build
            #   run: | 
            #     cd ${{github.repository}}
            #     hugo

            # - name: Verify artifacts
            #   run: ls -la public


              

